<h1 id="tocheading">Table of Contents</h1>
<div id="toc"></div>

In [1]:
#Python is a programming language widely used for machine learning
#Python is an open source tool
#Jupyter provides GUI interface for python programming in browser
#Python libraries like numpy,panda provide predefined functions for easy programming ex calculation of mean,variance etc
#Anaconda is widely recognized software distributor which installs Python, Jupyter and important python libraries



In [69]:
%%javascript
$.getScript('https://kmahelona.github.io/ipython_notebook_goodies/ipython_notebook_toc.js')


<IPython.core.display.Javascript object>

In [1]:
#Let's print hello world using print command
print("hello world")


hello world


In [2]:
##Let's print hello and world in two lines using newline operator
print("hello \nworld")

hello 
world


In [3]:
##let's print hello world using tab space operator
print("hello\tworld")

hello	world


In [4]:
##lets pass multiple strings to print statement with default separator as space and separator as -
print("hello","world")
print("hello","world","abc","def",sep = '-',end = '!')

SyntaxError: invalid syntax (<ipython-input-4-bf489bc96099>, line 3)

In [5]:
# Why numpy ?

print("1) Numpy is predefined library available for python programmers \n2) Numpy is implemented in C whose performance is better for vector operations\n\tif you are summing up two arrays the addition will be performed with the specialized CPU vector operations\n\tinstead of calling the python implementation of int addition in a loop")



1) Numpy is predefined library available for python programmers 
2) Numpy is implemented in C whose performance is better for vector operations
	if you are summing up two arrays the addition will be performed with the specialized CPU vector operations
	instead of calling the python implementation of int addition in a loop


In [6]:
# Why not C programming over python for machine learning?
print("1) C has higher performance but it is not object oriented programming\n2) Python has object oriented programming which uses numpy based on C programming for faster functions")


1) C has higher performance but it is not object oriented programming
2) Python has object oriented programming which uses numpy based on C programming for faster functions


In [7]:
# What is vector and matrix
print("Maxtrix is group of homogenous elements arranged in rows and columns\n\t vector is one row or one column\n\t Matrix is denoted as X and subscript X11 denotes element\n\t Zero matrx has all elements as zero ]n]t Identity elemenrs has diagonlaa elements as  and rest a 0")

Maxtrix is group of homogenous elements arranged in rows and columns
	 vector is one row or one column
	 Matrix is denoted as X and subscript X11 denotes element
	 Zero matrx has all elements as zero ]n]t Identity elemenrs has diagonlaa elements as  and rest a 0


In [8]:
#Initializing 1 dimensional array which is a matrix if elements are of same type
import numpy as np 
a = np.array([1,2,3]) 
print a

[1 2 3]


In [35]:
#Initializing two dimensional array 
import numpy as np 
a = np.array([[1,2,3],[3,4,5]]) 
a

array([[1, 2, 3],
       [3, 4, 5]])

In [38]:
#Giving dimension as input for an array
import numpy as np 
a = np.array([1, 2, 3,4,5], ndmin = 2) 
print a

[[1 2 3 4 5]]


In [39]:
# using array-scalar type 
import numpy as np 
dt = np.dtype(np.int32) 
print dt

int32


In [40]:
#int8, int16, int32, int64 can be replaced by equivalent string 'i1', 'i2','i4', etc. 
import numpy as np 

dt = np.dtype('i4')
print dt 


int32


In [41]:
# first create structured data type 
import numpy as np 
dt = np.dtype([('age',np.int8)]) 
print dt 

[('age', 'i1')]


In [42]:
# now apply it to ndarray object 
import numpy as np 

dt = np.dtype([('age',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt) 
print a

[(10,) (20,) (30,)]


In [47]:
# file name can be used to access content of age column 
import numpy as np 

dt = np.dtype([('age',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt) 
print a['age']

[10 20 30]


In [48]:
#The following examples define a structured data type called student with a string field 'name',
# an integer field 'age' and a float field 'marks'. This dtype is applied to ndarray object.
import numpy as np 
student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
print student

[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]


In [49]:
import numpy as np 

student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
a = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype = student) 
print a

[('abc', 21, 50.) ('xyz', 18, 75.)]


In [51]:
print(a['name'])

['abc' 'xyz']


In [1]:
#fetech shape of n dimensional array rows,columns are given 
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
print a.shape

(2L, 3L)


In [2]:
#Decide shape of an n dimensional array now of rows and columns
# Array of size two are considered 
import numpy as np 

a = np.array([[1,2,3],[4,5,6]]) 
a.shape = (3,2) 
print a 

[[1 2]
 [3 4]
 [5 6]]


In [3]:
#NumPy also provides a reshape function to resize an array.
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
b = a.reshape(3,2) 
print b


[[1 2]
 [3 4]
 [5 6]]


In [7]:
# this is one dimensional array 
import numpy as np 
a = np.arange(24) 
a.ndim  

# now reshape it 

b = a.reshape(2,4,3) 
print b.size
# b is having three dimensions

24


In [9]:
# dtype of array is int8 (1 byte) 
import numpy as np 
x = np.array([1,2,3,4,5], dtype = np.int8) 
print x.itemsize



1


In [8]:

# dtype of array is now float32 (4 bytes) 
import numpy as np 
x = np.array([1,2,3,4,5], dtype = np.float32) 
print x.itemsize

4


In [11]:
#How to make an array non editable
x.flags["WRITEABLE"] =  False 

In [13]:
x[0]=2

ValueError: assignment destination is read-only

In [14]:
# array of five ones. Default dtype is float 
import numpy as np 
x = np.ones(5) 
print x

[1. 1. 1. 1. 1.]


In [15]:
import numpy as np 
x = np.ones([2,2], dtype = int) 
print x

[[1 1]
 [1 1]]


In [16]:
# creating ndarray from tuple 
import numpy as np 

x = (1,2,3) 
a = np.asarray(x) 
print a

[1 2 3]


In [25]:
# ndarray from list of tuples 
import numpy as np 
x = [(1,2,3),(4,5)] 
a = np.asarray(x) 
print a


[(1, 2, 3) (4, 5)]


In [22]:
#create ndarray from strings
import numpy as np 
s = 'Hello World' 
a = np.frombuffer(s, dtype = 'S1') 
print a

['H' 'e' 'l' 'l' 'o' ' ' 'W' 'o' 'r' 'l' 'd']


In [26]:
# use iterator to create ndarray 
#step1 create list object using range function 
import numpy as np 
list = range(5) 
print list

[0, 1, 2, 3, 4]


In [27]:
# step2 obtain iterator object from list 
import numpy as np 
list = range(5) 
it = iter(list)  

# use iterator to create ndarray 
x = np.fromiter(it, dtype = float) 
print x

[0. 1. 2. 3. 4.]


In [28]:
# start and stop parameters set 
import numpy as np 
x = np.arange(10,20,2) 
print x

[10 12 14 16 18]


In [31]:
#linspace allows you to create ndrray mention no o elements required between start and stop
import numpy as np 
x = np.linspace(10,20,7) 
print x


[10.         11.66666667 13.33333333 15.         16.66666667 18.33333333
 20.        ]


In [32]:
#Create ndrarray of log values between given range
import numpy as np 
# default base is 10 
a = np.logspace(1.0, 2.0, num = 10) 
print a

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [35]:
#Slicing item from numpy array
a = np.arange(10) 
b = a[5] 
print("the fifth element is",b)

('the fifth element is', 5)


In [36]:
# slice items starting from index 

print a[2:]

[2 3 4 5 6 7 8 9]


In [37]:
# slice items between indexes 
print a[2:5]

[2 3 4]


In [40]:
#Slicing ndarray
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print a  

# slice items starting from index
print 'Now we will slice the array from the index a[1:]' 
print a[1:]

[[1 2 3]
 [3 4 5]
 [4 5 6]]
Now we will slice the array from the index a[1:]
[[3 4 5]
 [4 5 6]]


In [44]:
# array to begin with 
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

print 'Our array is:' 
print a 
print '\n'  

# this returns array of items in the second column 
print 'The items in the second column are:'  
print a[0:,1] 
print '\n'  



Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


The items in the second column are:
[2 4 5]


The items in the second row are:
[3 4 5]


The items column 1 onwards are:
[[2 3]
 [4 5]
 [5 6]]
[[2 3]
 [4 5]
 [5 6]]


In [45]:
# Now we will slice all items from the second row 
print 'The items in the second row are:' 
print a[1,] 
print '\n'  

# Now we will slice all items from column 1 onwards 
print 'The items column 1 onwards are:' 
print a[0:,1:]
#or
print a[...,1:]

The items in the second row are:
[3 4 5]


The items column 1 onwards are:
[[2 3]
 [4 5]
 [5 6]]
[[2 3]
 [4 5]
 [5 6]]


In [47]:
#Fetch specfic element from each row
#First array specifies record index second array specifies which column position should be displayed respectively
x = np.array([[1, 2], [3, 4], [5, 6]]) 
y = x[[0,1,2], [0,1,0]] 
print y

[1 4 5]


In [49]:
rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]])
rows

array([[0, 0],
       [3, 3]])

In [61]:
#Boolean Indexing
import numpy as np 
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 

print 'Our array is:' 
print x 
print '\n'  

# Now we will print the items greater than 5 
print 'The items greater than 5 are:' 
print x[x > 5]

Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


The items greater than 5 are:
[ 6  7  8  9 10 11]


In [62]:
#Checking nan condition
import numpy as np 
a = np.array([np.nan, 1,2,np.nan,3,4,5]) 
print a[~np.isnan(a)]

[1. 2. 3. 4. 5.]


In [63]:
#array multiplications
import numpy as np 

a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b 
print c

[ 10  40  90 160]


In [64]:
import numpy as np 
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  
   
print 'First array:' 
print a 
print '\n'  
   
print 'Second array:' 
print b 
print '\n'  
   
print 'First Array + Second Array' 
print a + b


First array:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


Second array:
[1. 2. 3.]


First Array + Second Array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [68]:
#How to iterate through an array and use Transpose funation
import numpy as np 
a = np.arange(0,60,5) 
a = a.reshape(3,4) 
   
print 'Original array is:'
print a 
print '\n'  
   
print 'Transpose of the original array is:' 
b = a.T 
print b 
print '\n'  
   
print 'Modified array is:' 
for x in np.nditer(b): 
   print x

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Transpose of the original array is:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


Modified array is:
0
5
10
15
20
25
30
35
40
45
50
55


In [85]:
#iterating two arrays
import numpy as np 
a = np.arange(0,80,5) 
a = a.reshape(4,4) 

print 'First array is:' 
print a 
print '\n'  

print 'Second array is:' 
b = np.array([1, 2, 3, 4], dtype = int) 
print b  
print '\n' 

print 'Modified array is:' 
for x,y in np.nditer([a,b]): 
   print "%d:%d" % (x,y),


First array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]
 [60 65 70 75]]


Second array is:
[1 2 3 4]


Modified array is:
0:1 5:2 10:3 15:4 20:1 25:2 30:3 35:4 40:1 45:2 50:3 55:4 60:1 65:2 70:3 75:4


In [99]:
a = np.array(111)
b = np.array([1,2])
c = np.array([[1,2], [4,5]])
d = np.array([[1,2,3,], [4,5]])
print a.ndim, b.ndim, c.ndim, d.ndim

#outputs: 0 1 2 1

0 1 2 1
()


In [100]:
#Creating arrays
a = np.array([1,2,3])

b = np.array([(1.5,2,3), (4,5,6)], dtype = float)


In [105]:
len(b)# no of elements in a dimension
b.size

6

In [9]:
#What is pandas in python
print("Pandas is a popular Python package for data science, and with good reason:\n it offers powerful, expressive and flexible data structures that make data manipulation and analysis easy, among many other things.\n The DataFrame is one of these structures.")

Pandas is a popular Python package for data science, and with good reason:
 it offers powerful, expressive and flexible data structures that make data manipulation and analysis easy, among many other things.
 The DataFrame is one of these structures.


In [15]:
# The Pandas library is usually imported under the alias pd
import pandas as pd
print("mong the many things that can serve as input to make a ‘DataFrame’, a NumPy ndarray is one of them. To make a data frame from a NumPy array, \nyou can just pass it to the DataFrame() function in the data argument.")

mong the many things that can serve as input to make a ‘DataFrame’, a NumPy ndarray is one of them. To make a data frame from a NumPy array, 
you can just pass it to the DataFrame() function in the data argument.


In [16]:
data = np.array([['','Col1','Col2'],
                ['Row1',1,2],
                ['Row2',3,4]])
                
print(pd.DataFrame(data=data[1:,1:],
                  index=data[1:,0],
                  columns=data[0,1:]))

     Col1 Col2
Row1    1    2
Row2    3    4


In [27]:
print(data[1:,0])

['Row1' 'Row2']


In [30]:
df = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6]]))

# Use the `shape` property
print(df.shape)

# Or use the `len()` function with the `index` property
print(len(df.index))

(2, 3)
2


In [40]:
#Height of data frame which will exclude nan values
df[0].count()

2

In [41]:
list(df.columns.values)

[0, 1, 2]

In [67]:
nparray = np.array([['A','B','C'],
                [1,2,3],
                [4,5,6],
                [6,7,8]])
df = pd.DataFrame( nparray)

#Use iloc to select a row
df.iloc[0]
#use loc to select column
df.loc[:,0:]




0  1  2
0  A  B  C
1  1  2  3
2  4  5  6
3  6  7  8

In [71]:
## Difference between indexing loc[] and iloc[]
df = pd.DataFrame(data=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), index= [2, 'A', 4], columns=[48, 49, 50])

# Pass `2` to `loc`
print(df.loc[2])

# Pass `2` to `iloc`
print(df.iloc[2])



48    1
49    2
50    3
Name: 2, dtype: int32
48    7
49    8
50    9
Name: 4, dtype: int32


In [87]:
##Adding column to data frame
df = pd.DataFrame(data=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), columns=['A', 'B', 'C'])

# Use `.index`
df['D'] = df.index

# Print `df`
print(df)
 

   A  B  C  D
0  1  2  3  0
1  4  5  6  1
2  7  8  9  2


In [89]:
# Study the DataFrame `df`
print(df)

# Append a column to `df`
df.loc[:, 4] = pd.Series(['5', '6','7'], index=df.index)

# Print out `df` again to see the changes
print(df)

   A  B  C  D
0  1  2  3  0
1  4  5  6  1
2  7  8  9  2
   A  B  C  D  4
0  1  2  3  0  5
1  4  5  6  1  6
2  7  8  9  2  7


In [90]:
## Resetting Index
print(df)

# Use `reset_index()` to reset the values
df_reset = df.reset_index(level=0, drop=True)

# Print `df_reset`
print(df_reset)

   A  B  C  D  4
0  1  2  3  0  5
1  4  5  6  1  6
2  7  8  9  2  7
   A  B  C  D  4
0  1  2  3  0  5
1  4  5  6  1  6
2  7  8  9  2  7


In [91]:
### Index drop and inplace
print("Note how you use the drop argument to indicate that you want to get rid of the index that was there. If you would have used inplace, the original index with floats is added as an extra column to your DataFrame.")

Note how you use the drop argument to indicate that you want to get rid of the index that was there. If you would have used inplace, the original index with floats is added as an extra column to your DataFrame.


In [92]:
##Delete Indices, Rows or Columns From a Pandas Data Frame
####Check out the DataFrame `df`
print(df)

####Drop the column with label 'A'                  
df.drop('A', axis=1, inplace=True)

####Drop the column at position 1
df.drop(df.columns[[1]], axis=1)

   A  B  C  D  4
0  1  2  3  0  5
1  4  5  6  1  6
2  7  8  9  2  7


B  D  4
0  2  0  5
1  5  1  6
2  8  2  7

In [93]:
###Removing row from data frame
# Check out your DataFrame `df`
print(df)

# Drop the duplicates in `df`
df.drop_duplicates([48], keep='last')

   B  C  D  4
0  2  3  0  5
1  5  6  1  6
2  8  9  2  7


KeyError: Int64Index([48], dtype='int64')

In [97]:
## Setting pandas option
pd.set_option('display.notebook_repr_html', False)
pd.set_option('display.max_columns', 10)
pd.set_option('display.max_rows', 10)  


OptionError: 'You can only set the value of existing options'

In [105]:
###Pandas Seres object
from pandas import DataFrame,Series
print("Series is the base data structure for pandas similar to numpy array with index capabilities")
#### Creating data frame with series
s = Series([1, 2, 3, 4])
print(s)
#### printing rows with label 3,4
s[[1,3]]



Series is the base data structure for pandas similar to numpy array with index capabilities
0    1
1    2
2    3
3    4
dtype: int64


1    2
3    4
dtype: int64

In [111]:
#### Creating series with index
s = Series([1,2,3,4], index=['a','b','c','d'])
s
print("data in series can now be accessed using alpha numeirc index")
s[['a','a']]


data in series can now be accessed using alpha numeirc index
passing list of integers 


b    2
c    3
dtype: int64

In [112]:
print("passing list of integers to alphanunmeric index series then 0 index is considered")
s[[1,2]]


passing list of integers to alphanunmeric index series then 0 index is considered


b    2
c    3
dtype: int64

In [113]:
print("Print index of series")
s.index

Print index of series


Index([u'a', u'b', u'c', u'd'], dtype='object')

In [116]:
print("create a time series")
dates = pd.date_range('2014-07-01', '2014-07-06')
dates

create a time series


DatetimeIndex(['2014-07-01', '2014-07-02', '2014-07-03', '2014-07-04',
               '2014-07-05', '2014-07-06'],
              dtype='datetime64[ns]', freq='D')

In [119]:
####create a Series with values (representing temperatures)  for each date in the index  

temps1 = Series([80, 82, 85, 90, 83, 87],index = dates)
temps1

2014-07-01    80
2014-07-02    82
2014-07-03    85
2014-07-04    90
2014-07-05    83
2014-07-06    87
Freq: D, dtype: int64

In [120]:
print("calculate mean of temperature i.e Avg temperature on give dates(index)")
temps1.mean()

calculate mean of temperature i.e Avg temperature on give dates(index)


84.5

In [122]:
print("create seconds series with the same dates as index")
temps2 = Series([70, 75, 69, 83, 79, 77],index = dates)  
print("the following aligns the two by their index values \n and calculates the difference at those matching labels") 
temp_diffs = temps1 - temps2   
temp_diffs

create seconds series with the same dates as index
the following aligns the two by their index values 
 and calculates the difference at those matching labels


2014-07-01    10
2014-07-02     7
2014-07-03    16
2014-07-04     7
2014-07-05     4
2014-07-06    10
Freq: D, dtype: int64

In [124]:
print("First access temp using date index and later by integer index")
print(temp_diffs['2014-07-03'])
print(temp_diffs[2])

First access temp using date index and later by integer index
16
16


In [142]:
print("append new item by adding new date for a series")
x = temp_diffs
x['2014-07-07'] = 10

append new item by adding new date for a series


In [144]:
### Pandas Dataframe
print("pandas Series represents a single array of values, with an index label for each value. If you want to have more than one Series of data that is aligned by a common index, then a pandas DataFrame is used")

pandas Series represents a single array of values, with an index label for each value. If you want to have more than one Series of data that is aligned by a common index, then a pandas DataFrame is used


In [146]:
#### Creating data frame with two columns
temps_df = DataFrame({'Missoula': temps1,'Philadelphia': temps2})   
temps_df

            Missoula  Philadelphia
2014-07-01        80            70
2014-07-02        82            75
2014-07-03        85            69
2014-07-04        90            83
2014-07-05        83            79
2014-07-06        87            77

In [159]:
#### Selecting columns in data frame
print("Print specifc column:\n\t print(temps_df['Missoula'])\n\n")
print(temps_df['Missoula'])
print("Print two or more columns:\n\t print(temps_df[['Missoula','Philadelphia']])\n\n")
print(temps_df[['Missoula','Philadelphia']])
print("Print data frame:\n\t print(temps_df)\n\n")
print(temps_df)
print("Print column using dot operator if no spaces are present:\n\t print(temps_df.Missoula)\n\n")
print(temps_df.Missoula)

Print specifc column:
	 print(temps_df['Missoula'])


2014-07-01    80
2014-07-02    82
2014-07-03    85
2014-07-04    90
2014-07-05    83
2014-07-06    87
Freq: D, Name: Missoula, dtype: int64
Print two or more columns:
	 print(temps_df[['Missoula','Philadelphia']])


            Missoula  Philadelphia
2014-07-01        80            70
2014-07-02        82            75
2014-07-03        85            69
2014-07-04        90            83
2014-07-05        83            79
2014-07-06        87            77
Print data frame:
	 print(temps_df)


            Missoula  Philadelphia
2014-07-01        80            70
2014-07-02        82            75
2014-07-03        85            69
2014-07-04        90            83
2014-07-05        83            79
2014-07-06        87            77
Print column using dot operator if no spaces are present:
	 print(temps_df.Missoula)


2014-07-01    80
2014-07-02    82
2014-07-03    85
2014-07-04    90
2014-07-05    83
2014-07-06    87
Freq: D, Name